spring.application.name=wec_ssvp

# Conexão com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wec_ssvp
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true